name: "Compatibility: Elixir"
on:
  push:
    branches:
      - master
      - release/*

jobs:
  test_on_source:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    name: "[${{matrix.otp}}/${{matrix.elixir}}] Elixir ${{matrix.repo_branch}} source code analysed by Credo [OTP/Elixir]"
    strategy:
      matrix:
        otp: [20.3, 21.3, 22.2, 23]
        elixir: [1.7.4, 1.8.2, 1.9.4, 1.10.4, 1.11.2]
        exclude:
          - otp: 23
            elixir: 1.7.4
          - otp: 23
            elixir: 1.8.2
          - otp: 23
            elixir: 1.9.4
          - otp: 20.3
            elixir: 1.10.4
          - otp: 20.3
            elixir: 1.11.2
        repo_url: ["https://github.com/elixir-lang/elixir.git"]
        repo_branch: ["v1.10", "master"]
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: mkdir -p tmp
      - run: git clone ${{matrix.repo_url}} tmp/${{matrix.repo_branch}} --depth=1 --branch ${{matrix.repo_branch}}
      - run: mix credo tmp/${{matrix.repo_branch}} --strict --mute-exit-status
